//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartdiff.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smartdiff.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:DTS=&quot;www.microsoft.com/SqlServer/Dts&quot;&gt;
        ///	&lt;xsl:output cdata-section-elements=&quot;ProjectItem arrayElement&quot;/&gt;
        ///
        ///	&lt;xsl:template match=&quot;node()&quot;&gt;
        ///		&lt;xsl:copy&gt;
        ///      &lt;!-- sort attributes by name --&gt;
        ///      &lt;xsl:apply-templates select=&quot;@*&quot;&gt;
        ///        &lt;xsl:sort order=&quot;ascending&quot; select=&quot;name()&quot;/&gt;
        ///      &lt;/xsl:apply-templates&gt;
        ///      
        ///      &lt;!-- leave default sort order --&gt;
        ///			&lt;xsl:apply-temp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmartDiffDtsx {
            get {
                return ResourceManager.GetString("SmartDiffDtsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:dwd=&quot;http://schemas.microsoft.com/DataWarehouse/Designer/1.0&quot; xmlns:SSAS=&quot;http://schemas.microsoft.com/analysisservices/2003/engine&quot; xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:ddl200=&quot;http://schemas.microsoft.com/analysisservices/2010/engine/200&quot;&gt;
        ///
        ///	&lt;xsl:output cdata-section-elements=&quot;SSAS:Text&quot;/&gt;
        ///
        ///	&lt;xsl:template match=&quot;no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmartDiffSSAS {
            get {
                return ResourceManager.GetString("SmartDiffSSAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:SSRS2005=&quot;http://schemas.microsoft.com/sqlserver/reporting/2005/01/reportdefinition&quot; xmlns:SSRS2008=&quot;http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition&quot;&gt;
        ///
        ///  &lt;xsl:output cdata-section-elements=&quot;SSRS2005:Code SSRS2008:Code SSRS2005:CommandText SSRS2008:CommandText&quot;/&gt;
        ///  
        ///  &lt;xsl:template match=&quot;node()&quot;&gt;
        ///		&lt;xsl:copy&gt;
        ///
        ///      &lt;!-- sort attributes by name --&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmartDiffSSRS {
            get {
                return ResourceManager.GetString("SmartDiffSSRS", resourceCulture);
            }
        }
    }
}
